M48
; DRILL file {KiCad 9.0.3} date 2026-05-17T22:53:57+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-17T22:53:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X110.0Y-75.0
X110.0Y-157.0
X162.0Y-75.0
X162.0Y-157.0
M30
